### ISSUE TITLE
Add scikit-image

### ISSUE THREAD

**Issue by MaokaiLin** [Black-Milk/Dash-Docset#2]
Sorry for separate my requests into two issues, but I guess they are different requests. :)

Could you add a dash doc set for scikit-image? (http://scikit-image.org/) Thanks a lot!

**Comment by Black-Milk** [comment]
Different requests or inquiries are best posted as separate issues, so you did fine. I'll look into the documentation source and see how I can bundle it into a docset this coming week.

**Comment by Black-Milk** [comment]
I just uploaded a Scikit-image 0.9.x docset into the repo. Feel free to try it and let me know if it works for you.

**Comment by MaokaiLin** [comment]
Works like a charm! Thanks a lot!
